### ISSUE TITLE
reading-listening-create front-end

### ISSUE THREAD

**Issue by Farhalsada** [bahrain-uob/gen-ai-moe-challenge#67] opened 2024-04-18 12:41 UTC
We already done with the front end but having a problem (sub-question with multiple inputs are treated as one) @cerashdan

**Comment by cerashdan** [comment] 2024-05-07 08:23
is this a duplicate of #150 ?

**Comment by Farhalsada** [comment] 2024-05-07 08:28
Yes

**Closed as completed** 2024-06-14 11:39 UTC
